%:
	+$(MAKE) $@ -C 01_intro
	+$(MAKE) $@ -C 02_arrays
	+$(MAKE) $@ -C 03_arrays_and_vectors
	+$(MAKE) $@ -C 06_linked_list
	+$(MAKE) $@ -C 07_vector -f GNUmakefile
	+$(MAKE) $@ -C 09_count_operations/count_operations/
	+$(MAKE) $@ -C 09_count_operations/file_io/
